CREATE TABLE [dbo].[Tax]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Code] VARCHAR(50) NOT NULL UNIQUE, 
    [CGST] DECIMAL(5, 2) NOT NULL DEFAULT  0, 
    [SGST] DECIMAL(5, 2) NOT NULL DEFAULT 0, 
    [IGST] DECIMAL(5, 2) NOT NULL DEFAULT 0, 
    [Status] BIT NOT NULL DEFAULT 1
)
