CREATE TABLE [dbo].[PurchaseDetail]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [PurchaseId] INT NOT NULL, 
    [RawMaterialId] INT NOT NULL, 
    [Quantity] DECIMAL(7, 3) NOT NULL DEFAULT 1, 
    [Rate] MONEY NOT NULL, 
    [BaseTotal] MONEY NOT NULL DEFAULT 0, 
    [DiscPercent] DECIMAL(5, 2) NOT NULL DEFAULT 0, 
    [DiscAmount] MONEY NOT NULL DEFAULT 0,
    [AfterDiscount] MONEY NOT NULL DEFAULT 0, 
    [CGSTPercent] DECIMAL(5, 2) NOT NULL DEFAULT 0, 
    [CGSTAmount] MONEY NOT NULL DEFAULT 0,
    [SGSTPercent] DECIMAL(5, 2) NOT NULL DEFAULT 0, 
    [SGSTAmount] MONEY NOT NULL DEFAULT 0, 
    [IGSTPercent] DECIMAL(5, 2) NOT NULL DEFAULT 0, 
    [IGSTAmount] MONEY NOT NULL DEFAULT 0, 
    [Total] MONEY NOT NULL DEFAULT 0, 
    [Status] BIT NOT NULL DEFAULT 1, 
    CONSTRAINT [FK_PurchaseDetail_ToRawMaterial] FOREIGN KEY (RawMaterialId) REFERENCES [RawMaterial](Id), 
    CONSTRAINT [FK_PurchaseDetail_ToPurchase] FOREIGN KEY (PurchaseId) REFERENCES [Purchase](Id), 
)
