CREATE TABLE [dbo].[BillDetail]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [BillId] INT NOT NULL, 
    [ProductId] INT NOT NULL, 
    [Quantity] INT NOT NULL DEFAULT 1, 
    [Rate] MONEY NOT NULL, 
    [BaseTotal] MONEY NOT NULL DEFAULT 0, 
    [Instruction] VARCHAR(250) NOT NULL, 
    [Discountable] BIT NOT NULL DEFAULT 1,  
    [SelfDiscount] BIT NOT NULL DEFAULT 0, 
    [DiscPercent] DECIMAL(5, 2) NOT NULL DEFAULT 0, 
    [DiscAmount] MONEY NOT NULL DEFAULT 0, 
    [AfterDiscount] MONEY NOT NULL DEFAULT 0, 
    [CGSTPercent] DECIMAL(5, 2) NOT NULL DEFAULT 0, 
    [CGSTAmount] MONEY NOT NULL DEFAULT 0, 
    [SGSTPercent] DECIMAL(5, 2) NOT NULL DEFAULT 0, 
    [SGSTAmount] MONEY NOT NULL DEFAULT 0, 
    [IGSTPercent] DECIMAL(5, 2) NOT NULL DEFAULT 0, 
    [IGSTAmount] MONEY NOT NULL DEFAULT 0, 
    [Total] MONEY NOT NULL DEFAULT 0, 
    [Cancelled] BIT NOT NULL DEFAULT 0,
    [Status] BIT NOT NULL DEFAULT 1, 
    CONSTRAINT [FK_BillDetail_ToBill] FOREIGN KEY (BillId) REFERENCES [Bill](Id), 
    CONSTRAINT [FK_BillDetail_ToProduct] FOREIGN KEY (ProductId) REFERENCES [Product](Id)
)
